# Generated by Django 2.2 on 2021-07-24 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('buy_link', models.URLField(blank=True)),
                ('rules_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=255)),
                ('b_day', models.DateField()),
                ('about_me', models.TextField(blank=True)),
                ('player_type', models.CharField(blank=True, choices=[("I've Played Some Monopoly Before", "I've Played Some Monopoly Before"), ("I've Played Cards Against Humanity", "I've Played Cards Against Humanity"), ('I enjoy Playing Games with Friends', 'I enjoy Playing Games with Friends'), ('I Own Gloomhaven!', 'I Own Gloomhaven!'), ("Don't Bend the Cards!!", "Don't Bend the Cards!!"), ('Now I Just Need to Sleeve Everything...', 'Now I Just Need to Sleeve Everything...'), ("Wow...I've spent Too Much", "Wow...I've spent Too Much"), ('Superbacker on Kickstarter', 'Superbacker on Kickstarter'), ('Lord to Cardboard', 'Lord to Cardboard')], max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('games', models.ManyToManyField(related_name='types', to='meetup_app.Game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='user_favs',
            field=models.ManyToManyField(related_name='fav_games', to='meetup_app.User'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('time', models.TimeField()),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('attending', models.ManyToManyField(related_name='user_attending', to='meetup_app.User')),
                ('user_creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_events', to='meetup_app.User')),
            ],
        ),
    ]
